version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "4c0933d4b7205df0d561"
      POSTGRES_DB: automacao
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - migration-net

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    command: redis-server --requirepass "94dd25c5bf372906d8fb" --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - migration-net

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: always
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=automacao
      - DB_POSTGRESDB_USER=postgres
      - DB_POSTGRESDB_PASSWORD="4c0933d4b7205df0d561"
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - N8N_HOST=techinteligente.site
      - WEBHOOK_URL=https://techinteligente.site/
      - VUE_APP_URL_BASE_API=https://techinteligente.site/
    ports:
      - "5678:5678"
    labels:
      - traefik.enable=true
      - traefik.http.routers.n8n.rule=Host(`techinteligente.site`)
      - traefik.http.routers.n8n.entrypoints=https
      - traefik.http.routers.n8n.tls.certresolver=letsencrypt
      - traefik.http.services.n8n.loadbalancer.server.port=5678
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - postgres
      - redis
    networks:
      - migration-net

  waha:
    image: devlikeapro/waha
    container_name: waha
    restart: always
    environment:
      - WHATSAPP_DEFAULT_ENGINE=NOWEB
      - WAHA_DOWNLOAD_MEDIA=true
      - WAHA_DASHBOARD_ENABLED=true
      - WAHA_DASHBOARD_USERNAME=admin
      - WAHA_DASHBOARD_PASSWORD=techinteligente
      - WAHA_API_KEY=techinteligente
    ports:
      - "3000:3000"
    labels:
      - traefik.enable=true
      - traefik.http.routers.waha.rule=Host(`api.techinteligente.site`)
      - traefik.http.routers.waha.entrypoints=https
      - traefik.http.routers.waha.tls.certresolver=letsencrypt
      - traefik.http.services.waha.loadbalancer.server.port=3000
      # Waha precisa de sticky sessions para o QR Code tamb√©m
      - traefik.http.services.waha.loadbalancer.sticky.cookie=true
      - traefik.http.services.waha.loadbalancer.sticky.cookie.secure=true
    volumes:
      - waha_data:/app/.waha
    depends_on:
      - postgres
      - redis
  # networks: # Removendo duplicata, ja foi declarado acima
  #   - migration-net

volumes:
  postgres_data:
  n8n_data:
  redis_data:
  evolution_instances:


networks:
  migration-net:
    driver: bridge
